### ISSUE TITLE
android 4.4 崩溃

### ISSUE THREAD

**Issue by kongnanlive** [SuperKung/DashboardView#1]
06-30 11:30:46.524 30601-30601/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.anderson.example, PID: 30601
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.anderson.example/com.anderson.example.MainActivity}: android.view.InflateException: Binary XML file line #9: Error inflating class com.anderson.dashboardview.view.DashboardView
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2271)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2320)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:138)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5117)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.anderson.dashboardview.view.DashboardView
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                       at com.anderson.example.MainActivity.onCreate(MainActivity.java:15)
                                                       at android.app.Activity.performCreate(Activity.java:5340)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1099)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2235)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2320) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:138) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5117) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Constructor.constructNative(Native Method)
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                       at com.anderson.example.MainActivity.onCreate(MainActivity.java:15) 
                                                       at android.app.Activity.performCreate(Activity.java:5340) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1099) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2235) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2320) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:138) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5117) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.NoClassDefFoundError: com.anderson.dashboardview.Interpolator.SpringInterpolator
                                                       at com.anderson.dashboardview.view.DashboardView.<init>(DashboardView.java:69)
                                                       at com.anderson.dashboardview.view.DashboardView.<init>(DashboardView.java:77)
                                                       at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                       at com.anderson.example.MainActivity.onCreate(MainActivity.java:15) 
                                                       at android.app.Activity.performCreate(Activity.java:5340) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1099) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2235) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2320) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:138) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5117) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
已处理

**Comment by s13524801** [comment]
SpringInterpolator兼容性问题

已经解决
